import {
  createProfile,
  ensureDefaultProfile,
  listProfiles,
  renameProfile,
  upsertLibraryEntry,
  listLibraryEntries,
  updateLibraryEntry,
  deleteLibraryEntry,
  saveProgressRecord,
  loadProgressRecord,
  clearProgressRecord,
  saveLastOpenedPaper,
  loadLastOpenedPaper,
  saveAttemptRecord,
  listAttempts,
  updateAttemptRecord,
  deleteAttemptRecord,
} from '../indexedDb'

export const indexedDbAdapter = {
  listProfiles,
  createProfile,
  renameProfile,
  ensureDefaultProfile,
  upsertLibraryEntry,
  listLibraryEntries,
  updateLibraryEntry,
  deleteLibraryEntry,
  saveProgressRecord,
  loadProgressRecord,
  clearProgressRecord,
  saveLastOpenedPaper,
  loadLastOpenedPaper,
  saveAttemptRecord,
  listAttempts,
  updateAttemptRecord,
  deleteAttemptRecord,
}